<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="MySql.Data" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IDS.Extension\IDS.Extension.csproj" />
    <ProjectReference Include="..\IDS.Ioc\IDS.Ioc.csproj" />
    <ProjectReference Include="..\IDS.Security.IService\IDS.Security.IService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DAL\" />
  </ItemGroup>

</Project>
