<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HPSocket.Net" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="C:\Users\USER\.nuget\packages\hpsocket.net\6.0.2\build\..\runtimes\win-x64\native\HPSocket4C.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
